export const techDescriptionMap: Record<string, string> = {
  javascript: "A versatile programming language used for building interactive web applications.",
  typescript: "A typed superset of JavaScript that improves code reliability and developer productivity.",
  react: "A popular JavaScript library for building user interfaces with reusable components.",
  nextjs: "A React framework for building full-stack web applications with SSR and static generation.",
  nodejs: "A JavaScript runtime that enables server-side development using JavaScript.",
  bun: "A fast all-in-one JavaScript runtime, package manager, and bundler.",
  deno: "A secure modern runtime for JavaScript and TypeScript created by the creator of Node.js.",
  python: "A beginner-friendly and powerful programming language used in web development, AI, and automation.",
  java: "A widely used object-oriented programming language known for portability and scalability.",
  c: "A foundational systems programming language used for operating systems and embedded software.",
  "c++": "An extension of C that supports object-oriented and high-performance programming.",
  "c#": "A Microsoft-developed language commonly used for desktop, web, and game development.",
  php: "A server-side scripting language widely used for web development.",
  html: "The standard markup language used to structure web pages.",
  css: "A stylesheet language used to design and style web applications.",
  git: "A distributed version control system used to track changes in source code.",
  docker: "A platform for building, shipping, and running applications in containers.",
  mongodb: "A NoSQL document database designed for flexibility and scalability.",
  mysql: "A popular open-source relational database management system.",
  postgresql: "An advanced open-source relational database known for reliability and powerful features.",
  aws: "Amazon's cloud computing platform offering storage, compute, networking, and more.",
  firebase: "Google's backend platform for authentication, databases, hosting, and analytics.",
  graphql: "A query language and runtime for APIs that allows clients to request specific data.",
  vue: "A progressive JavaScript framework for building user interfaces.",
  tailwindcss: "A utility-first CSS framework for rapidly building custom user interfaces.",
  angular: "A TypeScript-based framework for building large-scale web applications.",
  jquery: "A JavaScript library that simplifies DOM manipulation and event handling.",
  sass: "A CSS preprocessor that adds variables, nesting, and other advanced features.",
  laravel: "A PHP framework known for elegant syntax and developer-friendly features.",
  rails: "A Ruby framework that emphasizes convention over configuration for web development.",
  redis: "An in-memory data store commonly used for caching, sessions, and real-time applications.",
  linux: "An open-source operating system widely used on servers, cloud infrastructure, and development environments.",
  jenkins: "An automation server used for continuous integration and continuous deployment (CI/CD).",
  kubernetes: "A container orchestration platform for deploying and managing applications at scale.",
  azure: "Microsoft's cloud computing platform for building, deploying, and managing applications.",
  gcp: "Google's cloud platform offering infrastructure, machine learning, and data services.",
  bitbucket: "A Git repository hosting service with built-in CI/CD and collaboration tools.",
  nginx: "A high-performance web server, reverse proxy, and load balancer.",
  blender: "An open-source 3D creation suite for modeling, animation, and rendering.",
  unity: "A popular game development engine for creating 2D, 3D, AR, and VR experiences.",
  unreal: "A powerful game engine used for high-end games, simulations, and visualizations.",
  swift: "Apple's modern programming language for iOS, macOS, watchOS, and tvOS development.",
  kotlin: "A modern JVM language officially supported for Android development.",
  go: "A statically typed programming language designed by Google for simplicity and performance.",
  rust: "A systems programming language focused on memory safety and performance.",
  dart: "A programming language developed by Google, primarily used with Flutter.",
  flask: "A lightweight Python web framework for building APIs and web applications.",
  django: "A high-level Python framework that encourages rapid and secure web development.",
  bootstrap: "A CSS framework for building responsive and mobile-first websites.",
  materialui: "A React component library that implements Google's Material Design system.",
  photoshop: "Adobe's industry-standard software for image editing and graphic design.",
  illustrator: "Adobe's vector graphics editor for creating logos, illustrations, and artwork.",
  xd: "Adobe's UI/UX design and prototyping tool.",
  premiere: "Adobe's professional video editing software.",
  figma: "A collaborative cloud-based design and prototyping platform.",
  inkscape: "A free and open-source vector graphics editor.",
  trello: "A project management tool based on boards, lists, and cards.",
  jira: "A project tracking and issue management platform popular among software teams.",
  heroku: "A cloud platform that simplifies application deployment and hosting.",
  elasticsearch: "A distributed search and analytics engine built for speed and scalability.",
  redux: "A predictable state management library commonly used with React.",
  threejs: "A JavaScript library for creating and rendering 3D graphics in the browser."
};